repos:
  - repo: local
    hooks:
      - id: laravel-pint
        name: laravel-pint
        entry: backend/vendor/bin/pint
        language: script
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
